### ISSUE TITLE
Setup & Tests

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#1]
- Set up the project with the required dependencies for smart contract development and testing.
- Create a skeleton for the event contract with constructor fields worldID address, reward contract address, appId, and actionId.
- Write unit tests for the base event construction.

**Comment by emarc99** [comment]
I'd like to handle this task.

**Comment by Ugo-X** [comment]
assigned, please join tg group: https://t.me/explorebeyondzerocheck

**Comment by emarc99** [comment]
Joined, thanks
