### ISSUE TITLE
Withdraw Functionality

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#10]
- Implement the withdraw function to allow event organizers to withdraw unclaimed rewards after a specified timeout period.
- Write unit tests for the withdraw function.
- Create a function to cancel and reclaim unclaimed rewards
- After a duration of 30 days have passed, the event creator should be able to cancel and reclaim rewards that were not claimed by event participants.

**Comment by mimisavage** [comment]
May I take care of this?

**Comment by Levi-Ojukwu** [comment]
Hello @Ugo I'd love to work on this!

## About Me 
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How To Tackle This Issue 
- Tackling this issue, first I will create a withdraw function to allow event organizers to withdraw unclaimed rewards after a specified timeout period.

- I will write a unit test for the withdraw function ensuring that the logics are functioning well 

If assigned this issue, I will ensure compliance with the team, following the team's guideline 

## ETA - 36 hours

**Comment by Ugo-X** [comment]
@Levi-Ojukwu Assigned, please join the Tg group here: @explorebeyondzerocheck
