### ISSUE TITLE
 Create Event

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#2]
- Build the createEvent function in the contract to create a new event with relevant details (e.g., name, description, timestamp, reward type).
- Write unit tests for the createEvent function.

**Comment by web3normad** [comment]
HI, I am a solidity developer and I can create this function and write a unit test for it within an hour.

**Comment by hoangkianh** [comment]
Could I be assigned to this?

**Comment by Ugo-X** [comment]
Assigned, please join tg group: https://t.me/explorebeyondzerocheck

**Comment by Ugo-X** [comment]
@web3normad Please what is the update?

**Comment by Jagadeeshftw** [comment]
Shall i take care of this issue as well @Ugo-X?
