### ISSUE TITLE
Update token reward contract

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#21]
We need to update our current token reward implementation. Instead of directly transferring rewards when a creator adds them for users, we want to:

1.⁠ ⁠Create a mapping to store the rewards
2.⁠ ⁠Add a getter function to view these rewards  
3.⁠ ⁠Implement a claim function that:
   - Checks the mapping for user rewards
   - Transfers the reward to the user when they claim it
   
   
   ## ETA - 18 hours

**Comment by danielrobotz** [comment]
I'd love to give this a go.

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through the codebase on GitHub and study the EventRewardManager contract
- I will then implement the update as stated in the description in the contract
- I will write a test to make sure the updates made are working perfectly

## ETA
18 hours as stated above

**Comment by Ugo-X** [comment]
@markdavid000 assigned
