### ISSUE TITLE
Create a function to cancel and reclaim unclaimed rewards 

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#23]
After a duration of 30 days have passed, the event creator should be able to cancel and reclaim rewards that were not claimed by event participants.

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through the codebase on GitHub and study the EventRewardManager contract
- I will then implement the update as stated in the description in the contract
- I will write a test to make sure the updates made are working perfectly

## ETA
10 hours as stated above

**Comment by Nityam573** [comment]
Could I take on this issue?

**Comment by ryzen-xp** [comment]
Can I take this from here?
