### ISSUE TITLE
 Event view functions

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#3]
- Add functionality to retrieve a single event by ID.
- Add functionality to retrieve all events.
- Write unit tests for viewing a single event and all events.

**Comment by martinvibes** [comment]
Hey @Ugo-X would like to work on this and improve my solidity skills would reach out to you if I need any help

**Comment by devJaja** [comment]
Hey, I am a smart contract developer.
I can write a function that will retrieve events both the single event by ID and all events using solidity. I will make sure i write unit tests for viewing single event and all events, to  verified the function is working perfect

**Comment by Akanimorex** [comment]
Hello @Ugo-X , I'd love to work on this issue

### About Me

My Name is Akanimo Rex and I am well versed  in writing efficient and gas-optimised   solidity  code, I am an alumni of web3bridge, one of the biggest web3 developers incubators in Africa.

###How I plan to Tackle the issue

- Tackling this issue, first I will create a `getEvent` function and the ID would be passed as a parameter and it would return the event details
- Then i would create a `getAllEvents` function and this would return all the events in  an  array

I will write unit tests to ensure these functions work properly

If assigned this issue, I will ensure compliance with the team, following the team's guideline

##ETA 1 hour

**Comment by Ugo-X** [comment]
> Hello @Ugo-X , I'd love to work on this issue
> 
> ### About Me
> My Name is Akanimo Rex and I am well versed in writing efficient and gas-optimised solidity code, I am an alumni of web3bridge, one of the biggest web3 developers incubators in Africa.
> 
> ###How I plan to Tackle the issue
> 
> * Tackling this issue, first I will create a `getEvent` function and the ID would be passed as a parameter and it would return the event details
> * Then i would create a `getAllEvents` function and this would return all the events in  an  array
> 
> I will write unit tests to ensure these functions work properly
> 
> If assigned this issue, I will ensure compliance with the team, following the team's guideline
> 
> ##ETA 1 hour

assigned, please join tg group: https://t.me/explorebeyondzerocheck
