### ISSUE TITLE
 Register for Event

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#4]
- Integrate World ID on-chain verification for event registration.
- Build the registerEvent function to allow participants to register for an event.
- Write unit tests for the registerEvent function.

**Comment by od-hunter** [comment]
Hello please can I be assigned this? I'm up for the task.

**Comment by Ugo-X** [comment]
> Hello please can I be assigned this? I'm up for the task.

assigned, please join tg group: https://t.me/explorebeyondzerocheck

**Comment by Nityam573** [comment]
Could I take on this issue?

**Comment by Jagadeeshftw** [comment]
I'd like to take this issue.

**Comment by Ugo-X** [comment]
@Jagadeeshftw Assigned, please join the Tg group here: https://t.me/explorebeyondzerocheck
