### ISSUE TITLE
Create an NFT contract with a claim function for minting NFTs to event participants. 

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#7]
- Ensure the claim function can only be called from the event contract.
- Ensure that participants can mint only 1 token at a time
- Write unit tests for the NFT contracts.

**Comment by psychemist** [comment]
I’d like to resolve this by creating an NFT contract that handles claims and permits participants to mint 1 token at a time from a collection. I would also write tests to validate full functionality.

**Comment by nonso7** [comment]
May I try my hand at this? I am very confident in writing erc721 contract.

**Comment by DuendexCR** [comment]
Let me handle this issue!

**Comment by Nityam573** [comment]
Could I take on this issue?

**Comment by hoangkianh** [comment]
I’d like to work on this. Est time is 2 days

**Comment by Ugo-X** [comment]
@hoangkianh assigned, please join Tg group here: https://t.me/explorebeyondzerocheck

**Comment by hoangkianh** [comment]
@Ugo-X thanks. Already in the group :) I will create a draft PR today
