### ISSUE TITLE
Build the token transfer logic function logic to transfer USDC or WLD tokens to the contract if the event reward type is token-based.

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Contracts#8]
- Write unit tests for token reward functionality.

**Comment by psychemist** [comment]
I'd be happy to do implement this function logic in Solidity and write adequate tests

**Comment by anihdev** [comment]
I'd be happy to do this. Im Anih Somadina, a backend developer with cairo and solidity experience. to tackle this,

### I'll take the following process

*  I will use OpenZeppelin's IERC20 interface for safeTransfer and standard token interactions
*  I will includes an enum to distinguish between token and non-token based rewards
*  Performs multiple validation checks:
*  Verifies reward type is token-based
*  Checks token support and allowance
*  Transfers tokens if the reward type is TOKEN
*  Emits an event with transfer details
*  then use safeTransfer() method to Perform token transfer with success check
*  I'll also write tests to check edge cases

**Comment by Ugo-X** [comment]
@psychemist assigned, please join tg group: https://t.me/explorebeyondzerocheck

**Comment by psychemist** [comment]
@Ugo-X joined, thanks!
